spring.application.name: pre-project-2-2-2
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pre-project-2-2-2
    username: postgres
    password: postgres
  jpa:
    show-sql: true

car:
  maxCars: 5
  sortFields: model,engine

loan:
  minimalincome: 40000
  minimalCarPrice: 1000000
  maxShare: 30